export const CONNECT_WALLET = 'CONNECT_WALLET'
export const SET_IS_CONNECTING_WALLET = 'SET_IS_CONNECTING_WALLET'
export const SET_WALLET_CONECTING_FINISHED = 'SET_WALLET_CONECTING_FINISHED'
export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS'