
export const INI_SOLANA_WEB3_CONNECTION = 'INI_SOLANA_WEB3_CONNECTION'
export const UPDATE_METADATA_MAPPED = 'UPDATE_METADATA_MAPPED'
export const ADD_CREATED_NFT = 'ADD_CREATED_NFT'
export const ADD_CREATED_MACHINE = 'ADD_CREATED_MACHINE'
